---
booktitle: Proceedings of the Workshop on the Causation and Prediction Challenge at
  WCCI 2008
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
volume: 3
year: '2008'
start: 2008-06-03
end: 2008-06-04
published: 2008-12-31
comments: false
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
shortname: CPC
bibsource: http://jmlr.csail.mit.edu/proceedings/
layout: proceedings
id: GuyonIACCGEPJSPSA2008
month: 0
cycles: false
editor:
- given: Isabelle
  family: Guyon
- given: Constantin
  family: Aliferis
- given: Greg
  family: Cooper
- given: André
  family: Elisseeff
- given: Jean-Philippe
  family: Pellet
- given: Peter
  family: Spirtes
- given: Alexander
  family: Statnikov
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Workshop on the Causation and Prediction Challenge at WCCI 2008
    Held in Hong Kong on 03-04 June 2008

  Published as Volume 3 by the Proceedings of Machine Learning Research on 31 December 2008.

  Volume Edited by:
    Isabelle Guyon
    Constantin Aliferis
    Greg Cooper
    André Elisseeff
    Jean-Philippe Pellet
    Peter Spirtes
    Alexander Statnikov

  Series Editors:
    Neil D. Lawrence
date_str: 03--04 Jun
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v3"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v3
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Causation and Prediction Challenge
  url: http://clopinet.com/isabelle/Projects/WCCI2008/
  location: Hong Kong
  dates:
  - 2008-06-03
  - 2008-06-04
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
