---
booktitle: Causation and Prediction Challenge (WCCI 2008)
series: Proceedings of Machine Learning Research
volume: 3
year: '2008'
start: 2008-06-03
end: 2008-06-04
published: 2008-12-31
comments: false
shortname: CPC
bibsource: http://jmlr.csail.mit.edu/proceedings/
layout: proceedings
id: GuyonIACCGEPJSPSA2008
month: 0
abstract: ''
sections: 
editor:
- given: Isabelle
  family: Guyon
- given: Constantin
  family: Aliferis
- given: Greg
  family: Cooper
- given: André
  family: Elisseeff
- given: J.-P.
  family: Pellet
- given: P.
  family: Spirtes
- given: A.
  family: Statnikov.
title: Causation and Prediction Challenge (WCCI 2008)
email: ''
description: Causation and Prediction Challenge (WCCI 2008), Hong Kong
url: http://proceedings.mlr.press
baseurl: "/v3"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v3
conference:
  name: Causation and Prediction Challenge (WCCI 2008)
  url: http://clopinet.com/isabelle/Projects/WCCI2008/
  location: Hong Kong
  dates:
  - 2008-06-03
  - 2008-06-04
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v3.bib
